const userActionTypes = {
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    UPDATE_USER_CART_START: 'UPDATE_USER_CART_START',
    UPDATE_USER_CART_SUCCESS: 'UPDATE_USER_CART_SUCCESS',
    UPDATE_USER_CART_FAILURE: 'UPDATE_USER_CART_FAILURE',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    REMOVE_ERROR: 'REMOVE_ERROR'
} 

export default userActionTypes;